start : expr
expr: "If(" expr "==" CONST "," expr "," expr ")"
      | "if(" expr "," expr "," expr ")"
      | "(" expr ")"
      | "(" expr "++" expr ")" triop expr 
      | expr binop expr 
      | unop expr 
      | CONST 
      | VAR

triop : "/" | "/s" | "%" | "%s"
binop : "+" | "-" | "*" | "&" | "|" | "^" | "<<" | ">>s" | ">>u"
unop : "-" | "~"

CONST : DIGIT+
VAR : "v" DIGIT+
YESNO : "yes" | "no"

%import common.DIGIT
%import common.NEWLINE
%import common.WS
%ignore WS
%ignore NEWLINE
